### ISSUE TITLE
Suggestion: Adding support for providers besides Shopfiy

### ISSUE THREAD

**Issue by sezze** [vercel/commerce#1000]
This is a huge task, although probably worth having an issue for it lying around.

# The problem
While Shopify is great, it's also never ideal to lock anyone into only one ecosystem.

# The solution
I would at least keep this in mind while laying down the foundation to make it possible to expand support for other platforms in the future.

As someone without too much e-commerce experience, I'm also curious about what Shopify had to offer that made you choose it for the integration over others. Purely its popularity?

**Comment by Terkinas** [comment]
I'm new to NextJS, so basically I can play around with this project as it's shopify based project?

**Comment by Ethan-Guest** [comment]
@sezze As Lee stated in the [release notes](https://github.com/vercel/commerce/releases/tag/v1), they are adopting a single-provider approach so they can focus on bringing the latest Next 13 features to the template without having to worry about conflicts and varying conventions from multiple providers. I think this is a great change, as we'll see faster updates and hopefully more features for the template. The Shopify Storefront API seems to be the most capable and flexible option that allows them to do that.

My team is currently using the v1 template with [Saleor](https://github.com/saleor/saleor-platform), which functions similarly to the Shopify Storefront API. We may consider creating a fork of v2 that integrates Saleor if others would find it useful. We're keeping a close eye on v2's progress to assess the amount of work needed for this, so I can't make any promises. Hope this helps! 👍

**Comment by osseonews** [comment]
I agree with @Ethan-Guest that a single-provider approach is much better. It is not too difficult to fork the repo to customize it for another provider. However, the choice of Shopify at the core provider is a strange one. Shopify has already launched Hydrogen on Remix, so why would anyone who uses Shopify use NextJsCommerce v2 (still in beta) over Hydrogen? At the same time, is there really any other ecommerce backend that you can feel confident building on right now where you can know for sure the company will be around 5 yrs?

Also, the decision to use the App folder for the cart appears to be a poor choice. I can see where the App folder can help with other storefront operations, but the cart? It doesn't work well at all in our tests and the performance of useSwr as used in V1 is far superior.  In general, useSwr is a production-ready, battle-tested library, that is perfect for cart operations. Hard to understand why they are throwing useSwr in the garbage to adopt a new approach that really provides zero performance benefits and actually performs rather poorly. Finally, Shopify tried for over a year with their internal dev team to develop a production-ready app using RSC and failed. They gave up and went with Remix because RSC simply didn't work well for certain ecommerce operations. They are experts in ecommerce. It is a bit odd that Vercel is attempting to build on RSC when Shopify failed. Does Vercel have some unique knowledge of RSC over Shopify developers?

**Comment by leerob** [comment]
We've been in touch with many of the v1 providers to chat with them about creating their own v2 forks. Stay tuned!

**Comment by sezze** [comment]
Great to hear that there's a plan! Sounds like a decent solution as long as the providers keep them up to date. Thank you and thank you to the others for your input.

**Comment by leerob** [comment]
https://github.com/vercel/commerce/pull/1008

**Comment by sezze** [comment]
> #1008

Heyyy awesome! 🎉 Great idea too to store them all in the README file.

**Comment by Giusti** [comment]
Hey, before changing to V2 there was a PR to support commerce tools, any plans already to provide a fork / demo utilising commerce tools?

**Comment by manovotny** [comment]
> does this work for bigcommerce?

We are working with the BigCommerce team as we speak on an updated version. Stay tuned...

> Hey, before changing to V2 there was a PR (#774) to support commerce tools, any plans already to provide a fork / demo utilizing commerce tools?

Vercel doesn't have any plans to add any more providers ourselves. However, we are more than happy to partner and work with any commerce provider to help them get a template up and running.

**Comment by RechargeTom** [comment]
@manovotny thanks for the reply! is there an older version that works with the public documentation? https://developer.bigcommerce.com/api-docs/storefronts/nextjs-commerce
or is that no longer possible?

**Comment by manovotny** [comment]
@RechargeTom you can use the old version as documented on the README. 

> Note: Looking for Next.js Commerce v1? View the [code](https://github.com/vercel/commerce/tree/v1), [demo](https://commerce-v1.vercel.store), and [release notes](https://github.com/vercel/commerce/releases/tag/v1)

**Comment by manovotny** [comment]
I am going to close this issue as there is [a plan and a path forward here](https://github.com/vercel/commerce/pull/1039) for how we're going to add alternative providers.
