### ISSUE TITLE
Sitemap required on deployment

### ISSUE THREAD

**Issue by alasdairkite93** [vercel/commerce#1213]
I am deploying this project using NextJS clone but when I click clone and deploy on: 'https://nextjs.org/commerce' I am getting the error message no sitemap as shown on print screen. 

As the whole project is hosted on Github and is used in the deployment of this application with for instance Shopify and Twitter can a sitemap please be added to the repository in order to make the 'Clone & Deploy' button work on: https://nextjs.org/commerce please. 

I do realise that the sitemap would change on an individual basis but having the file in there would make the button work at least.

![Screenshot 2023-10-02 at 16 10 18](https://github.com/vercel/commerce/assets/101645489/2c85116b-fa68-4666-b771-2190eb302514)

**Comment by manovotny** [comment]
@alasdairkite93 this is likely due to the `SHOPIFY_STOREFRONT_ACCESS_TOKEN` environment variable missing. The [Shopify integration guide](https://vercel.com/docs/integrations/shopify#configure-environment-variables) instructs you how to get this in your Shopify admin. If this doesn't work, please let me know, and we can troubleshoot further.

**Comment by leonnardovv** [comment]
I have the same issue and SHOPIFY_STOREFRONT_ACCESS_TOKEN is set.
Any updates on this?

**Comment by alasdairkite93** [comment]
Cloning the vercel github repository worked - however; it seemed as though the other github clone I had made was at fault. The site is now deployed.
