### ISSUE TITLE
502 BAD GATEWAY (installing to Vercel)

### ISSUE THREAD

**Issue by fandy** [vercel/commerce#196]
Getting this annoying error frequently when installing the app to Vercel. I installed it fine yesterday. Seems to be something that's down from BigCommerce's API?

![image](https://user-images.githubusercontent.com/19108762/107301338-4eac3e80-6a49-11eb-8104-5495d1e0bcc0.png)

**Comment by okbel** [comment]
We're checking with the team! Could you explain the steps to reproduce? Normal deployment of Next.js Commerce?

**Comment by chibicode** [comment]
Are you signing up to BigCommerce or are you logging in to an existing store?

<img width="696" alt="Screen Shot 2021-02-11 at 11 57 52 PM" src="https://user-images.githubusercontent.com/992008/107743012-f97c6100-6cc4-11eb-8ef7-8ab38a47c6f0.png">

**Comment by mike-j-king** [comment]
+1 seeing same issue. Error occurs after selecting any of my bigcommerce stores when logging in to an existing store

**Comment by amckemie** [comment]
@fandy @mike-j-king Thanks for bringing up this issue! We're digging into this on the BigCommerce side. In order to help facilitate this and hopefully get to a quicker resolution, can you provide steps to reproduce and any additional info from the console regarding the error (which API request is resulting in that error for example)? Thank you!

**Comment by okbel** [comment]
Looks like this has been solved already!
