### ISSUE TITLE
We don't want BigCommerce

### ISSUE THREAD

**Issue by fsuaterdogan** [vercel/commerce#197]
Hello, we are only working on a prototype project as a team. That's why we don't want to use BigCommerce. How can we remove BigCommerce from the project? I would be glad if you could help.

**Note: I cloned the project and changed .env.template to .env.local.**

Thanks

**Comment by wtLau** [comment]
I think it would be a good start to state what do you want from this project? Let's say if you don't want BigCommerce, do you want another eCommerce platform or just the UI of the app?

**Comment by JusticeBringer** [comment]
@wtLau Let's assume I would keep the UI of the app but implement my own functionality for the eCommerce platform. That would mean that I'm fetching the data from my Mongo database, display the products to the users and I would have Stripe integration for the payment. What would be the general steps to accomplish that?

**Comment by waynetheisinger** [comment]
@JusticeBringer - you might like to fork https://github.com/vendure-ecommerce/vendure as that is an ecommerce node based backend and according to the author "Vendure supports multiple databases. Currently it is tested with MySQL/MariaDB, PostgreSQL, SQLite and SQL.js. Since Vendure uses TypeORM to manage data access, it can theoretically also work with CockroachDB, Microsoft SQL Server and MongoDB, though these are as yet untested"

It should give you a large leg up on the sort of project you're describing.

That project also has a front-end in the works or you could hybrid your solution using vercel/commerce in the front and vendure-ecommerce in the back.

**Comment by okbel** [comment]
Hello! We're about to ship the agnostic branch and we will ship with Shopify and more providers. Thank you!
