### ISSUE TITLE
What is codegen.json used for?

### ISSUE THREAD

**Issue by FBosler** [vercel/commerce#203]
Amazing repo, documentation is a bit thin though :)
I was wondering what is `codegen.json` for? I ran `yarn generate` but got an error around authentication. On a closer look into codegen.json, it doesn't look like those credentials are actually being used?

**Comment by whatisaghostwriter** [comment]
Within codegen.json you have to replace the default config with your own websites auth and graphql api. 
"schema": {
    "https://{STORE-ID}.mybigcommerce.com/graphql": {
      "headers": {
        "Authorization": "Bearer {API-KEY}"
 }
}
From my understanding it generates the output schema.d.ts, schema.graphql files. I don't have in depth knowledge, but graphql provides a lot of benefits it just things like this that set you back. We have to understand this tool and its plugins in brevity because it shouldnt be this demanding to pull data.  https://github.com/dotansimha/graphql-code-generator#readme

**Comment by FBosler** [comment]
@whatisaghostwriter Seems like this is only working for BigCommerce right now though. For me it bugs out when trying to use it with Shopify (even after adjusting the paths accordingly).

```
$ graphql-codegen
  ✔ Parse configuration
  ❯ Generate outputs
    ❯ Generate ./framework/shopify/schema.d.ts
      ✔ Load GraphQL schemas
      ✖ Load GraphQL documents
        →           - ./framework/shopify/api/**/*.ts
        Generate
    ❯ Generate ./framework/shopify/schema.graphql
      ✔ Load GraphQL schemas
      ✖ Load GraphQL documents
        →           - ./framework/shopify/api/**/*.ts
        Generate
```

**Comment by FBosler** [comment]
@cond0r sorry to tag you out of the blue, but I recall you providing valuable input on another open issue and was wondering if you have a minute to help me better understand whats happening here, or what I would have to change to get this working.

I did change the `codegen.json` in accordance with your [PR](https://github.com/vercel/commerce/pull/285/files).

I am asking because Shopify recently added the option to also sell subscriptions through their checkout. However, doing so requires passing some information that does not seem to be present in the current type definitions.

Cheers

**Comment by cond0r** [comment]
@FBosler if you see on that PR, i had to change the queries too, so you have to apply that too, otherwise the command will throw you an error.

But are you sure you can use that in Storefront API ? I took a look, and doesn't seem to be available. I see they created a Subscription API for creating apps, but that is separated / different thing.

**Comment by FBosler** [comment]
@cond0r seems like you are right. It does not appear that the Storefront API supports subscriptions yet (I am still going to check, might be undocumented).

However, the [AJAX-Api](https://shopify.dev/docs/themes/ajax-api/reference/cart#add-a-selling-plan).

Could you explain the logic behind changing the queries? I.e. which conditions do they have to meet for the codegen to not throw an errorr.

Cheers

**Comment by cond0r** [comment]
@FBosler if you clone master now, you can run `yarn generate:shopify` and it will generate definitions & schema

**Comment by manovotny** [comment]
Hey there! Thank you for your contribution. We have decided to take Next.js Commerce in a new direction and will be closing out current PRs and issues due to this change. Please see this PR for more details: #966
