### ISSUE TITLE
Sign-up is not working

### ISSUE THREAD

**Issue by gr-qft** [vercel/commerce#24]
Whatever email and password given when signing-up, there's always the error message about passwords must be greater than 7 characters with at least a numeric character. It seems to me authentication is not fully implemented yet?

**Comment by okbel** [comment]
We just added an .env.template. Have you tried that? LMK!

**Comment by gr-qft** [comment]
@okbel I still have not been able to sign up, still seeing the same message (my password surely is longer than 7 chars and includes numbers).

**Comment by frannunezrivera** [comment]
I'm having this problem too:
@gr-qft  if you check in the bigcommerce - customers panel you will see your user has been created. I believe the problem is when logging in. (in this case probable after user is being created)

@okbel The sign-in hook is returning invalid credentials (error 400 : bad request) but the API request is returning an error 500. POST http://localhost:3000/api/bigcommerce/customers/login 500 (Internal Server Error). Not sure why because it looks the params are being passed correctly... I didn't have time to check the @bigcommerce npm package yet.

**Comment by okbel** [comment]
@gr-qft What data are you giving to sign up?
And yes, auth has been implemented. Try https://demo.vercel.store to check it out live.

Yeah, @frannunezrivera it's using those hooks so I think it may be masking some errors with the password lengths and criteria

**Comment by gr-qft** [comment]
@okbel The problem is not with the demo site. The problem occurred when I deployed vercel commerce repo on my vercel account. I still have a problem, but the deployed repo is 8d old, and I'm running into some deployment problem (hook, module etc.) so I cannot test it now.

**Comment by iamfeek** [comment]
mm yeah. I am facing the same problem as @gr-qft. 
Repo deployed 2 days ago, testing on local. 
.env areismatching that of Vercel's env vars.

**Comment by stevencmh** [comment]
> @okbel The problem is not with the demo site. The problem occurred when I deployed vercel commerce repo on my vercel account. I still have a problem, but the deployed repo is 8d old, and I'm running into some deployment problem (hook, module etc.) so I cannot test it now.

Hi, did you get this working? I'm seeing the same thing on my deployment.

**Comment by bobbiejaxn** [comment]
> > @okbel The problem is not with the demo site. The problem occurred when I deployed vercel commerce repo on my vercel account. I still have a problem, but the deployed repo is 8d old, and I'm running into some deployment problem (hook, module etc.) so I cannot test it now.
> 
> Hi, did you get this working? I'm seeing the same thing on my deployment.

I am having the same issue, unfortunately. Any advice on this?

**Comment by rezakalfane** [comment]
Hi,

I also still have the same issue. My .env.local file has been fetch using "vercel env pull .env.local", and everything runs fine on Vercel and locally, but I can't Signup / Signin...

Any idea?

Thanks!

Error: Internal server error
    at FetcherError.CommerceError [as constructor] (/Users/rkalfane/Workspace/commerce-4/node_modules/@bigcommerce/storefront-data-hooks/commerce/utils/errors.js:35:24)
    at new FetcherError (/Users/rkalfane/Workspace/commerce-4/node_modules/@bigcommerce/storefront-data-hooks/commerce/utils/errors.js:47:28)
    at /Users/rkalfane/Workspace/commerce-4/node_modules/@bigcommerce/storefront-data-hooks/api/utils/fetch-graphql-api.js:75:31
    at step (/Users/rkalfane/Workspace/commerce-4/node_modules/@bigcommerce/storefront-data-hooks/api/utils/fetch-graphql-api.js:44:23)
    at Object.next (/Users/rkalfane/Workspace/commerce-4/node_modules/@bigcommerce/storefront-data-hooks/api/utils/fetch-graphql-api.js:25:53)
    at fulfilled (/Users/rkalfane/Workspace/commerce-4/node_modules/@bigcommerce/storefront-data-hooks/api/utils/fetch-graphql-api.js:16:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  errors: [
    {
      message: 'Internal server error',
      path: [Array],
      locations: [Array]
    }
  ],
  status: 200
}

**Comment by adamhowell** [comment]
@rezakalfane Did you ever figure this out or hear anything back? I'm having this same issue locally as well.

**Comment by rezakalfane** [comment]
> @rezakalfane Did you ever figure this out or hear anything back? I'm having this same issue locally as well.

No, not yet... Maybe some authorization issues in my BigCommerce config... Everything works on the Vercel instance?

**Comment by hlopes** [comment]
Hi, I'm not sure if it helps, but here are my 2 cents on this:

The user is created successfully without any problems. However, when the login request is performed against the graphql endpoint (...framework/bigcommerce/api/customers/handlers/signup.ts), we're getting the following result:

`graphql url =  https://store-mhqee6hrg4-486614.mybigcommerce.com/graphql
query =
  mutation login($email: String!, $password: String!) {
    login(email: $email, password: $password) {
      result
    }
  }

variables =  {
  email: 'abc@some-domain.com',
  password: 'somepassword'
}
response json =  {
  "data": null,
  "errors": [
    {
      "message": "Internal server error",
      "path": [
        "login"
      ],
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ]
    }
  ]
}
`

On the other hand, the same problem occurs using the storefront api playground with the correct token (others requests works).

After some search, I've found this discussion https://support.bigcommerce.com/s/question/0D54O00006Sy9ecSAB/im-having-difficulty-with-the-storefront-graphql-customer-login, but it was inconclusive because resetting the customer password didn't work for me.

**Comment by okbel** [comment]
Seems heavily related to BigCommerce, but could you put a debugger there to at least see the error coming back from BC? cc @rezakalfane

**Comment by jackleblack** [comment]
Up

**Comment by frannunezrivera** [comment]
Ok, I could revisit this today and I've found the issue.

You just need to go to your store settings page [[youstore].mybigcommerce.com/manage/settings/store]([youstore].mybigcommerce.com/manage/settings/store) and disable maintenance mode. 

Although signup works, singing in while in maintenance mode returns this error with no context.

cc: @gr-qft I believe you can close this issue now.

Regards.

**Comment by gr-qft** [comment]
@frannunezrivera Thanks a lot for the hint, I've not had a chance to come back to this issue but I'll close it now. 

Best!

**Comment by wtLau** [comment]
Hi

I think sign up is not working again even on the live demo site [https://demo.vercel.store](https://demo.vercel.store)

On the live demo site, I am receiving 500 status code with `message: "An unexpected error occurred"` when signing up with a new account.

![image](https://user-images.githubusercontent.com/26396307/120747975-d87b8e00-c4b6-11eb-895b-b244ba34da84.png)


On my local site, I am using Shopify Storefront API. And I am getting `Customer accounts are disabled.` when I tried to sign up.

![image](https://user-images.githubusercontent.com/26396307/120748025-ec26f480-c4b6-11eb-9a6a-0bf3a23e84a9.png)

**Comment by cond0r** [comment]
@wtLau like error says, customer accounds are disabled. Enable it on Shopify.

https://help.shopify.com/en/manual/customers/customer-accounts

**Comment by wtLau** [comment]
@cond0r Thx! Never used Shopify before.... thought its a client error
