### ISSUE TITLE
Code-Gen not picking up templateSuffix shopify type

### ISSUE THREAD

**Issue by achadee** [vercel/commerce#269]
This is probably not a vercel/commerce issue, but posting here as it might help someone else with the same issue.

Im trying to add the `templateSuffix` type to a query, but code-gen has not included it in the `schema.d.ts` . Even after I manually add the type and query I get the error:

```
Error: Field 'templateSuffix' doesn't exist on type 'Collection'
```

it's worth noting that I can query other fields on the collection, and I can successfully query the templateSuffix using the exact same query on Shopify's playground.

query:
```ts
  query getSiteCollections($first: Int!, $cursor: String) {
    collections(first: $first, query: "published_status:published", after: $cursor) {
      edges {
        cursor
        node {
          id
          title
          handle
          templateSuffix
        }
      }
      pageInfo {
        hasNextPage
        hasPreviousPage
      }
    }
  }
```

Collection type (after I manually added the field in):

```ts
/** A collection represents a grouping of products that a shop owner can create to organize them or make their shops easier to browse. */
export type Collection = Node & {
  __typename?: 'Collection'
  /** Stripped description of the collection, single line with HTML tags removed. */
  description: Scalars['String']
  /** The description of the collection, complete with HTML formatting. */
  descriptionHtml: Scalars['HTML']
  /**
   * A human-friendly unique string for the collection automatically generated from its title.
   * Limit of 255 characters.
   */
  handle: Scalars['String']
  /** Globally unique identifier. */
  id: Scalars['ID']
  /** Image associated with the collection. */
  image?: Maybe<Image>
  /** List of products in the collection. */
  products: ProductConnection
  /** The collection’s name. Limit of 255 characters. */
  title: Scalars['String']
  /** The date and time when the collection was last modified. */
  updatedAt: Scalars['DateTime']

  templateSuffix?: Maybe<Scalars['String']>
}
```

**Comment by cond0r** [comment]
@achadee  it shows that error because it isn't supported in **Shopify Storefront API** https://shopify.dev/docs/storefront-api/reference . You successfully queried that into Shopify's Playground, because you used the **Admin API** Playground.

If you need to access the Admin API, you have to authenticate like it says here to get the access token:
https://shopify.dev/tutorials/authenticate-a-private-app-with-shopify-admin#make-authenticated-requests
and implement the queries by yourself, be careful to only query on server-side. To not expose it into client.

**Comment by achadee** [comment]
Ahh I feel so stupid! That makes so much sense. I always assumed the functionality was more or less the same for reading objects between the 2 API's

Thank you again! @cond0r

**Comment by achadee** [comment]
@cond0r is it secure/safe to code up an interface to the Admin API on the client as long as its run on SSR? I'm modifying the current interface with a "isAdmin" field that changes the query and headers

**Comment by cond0r** [comment]
@achadee Yes on SSR is safe... When i said client, i said more to not expose or use Admin API by replacing the fetcher and to use that api on search pages or on get checkout / cart. Because one of your users can see the request with token... But if you do it on SSR you are safe.

You can change  /framework/shopify/api/utils/fetch-graphql-api.ts file to use the Admin API by replacing the API_URL with the admin one,  then you do basic auth (link above) and change the headers on that file also with that token. 

But do NOT change the /framework/shopify/fetcher.ts this one happens on the client side for grabing the cart or search products. If you want to use Admin API here too.... than take a look how Bigcommerce provider does it,  instead of making graphql queries directly on client, you use the /api/ paths and make the query server side. 
For Storefront API queries was safe to do directly on the client.
