### ISSUE TITLE
Issues picking variants in the ProductView.

### ISSUE THREAD

**Issue by okbel** [vercel/commerce#317]
Description: Sometimes picking a color is not available in some size and still I'm allowed to add that product.

**Comment by drugan** [comment]
The same is here. I have a product with the following options:

- 
- **Color**: _Blue, Green, Yellow_
- **Size**: _Small, Medium, Large_
- 

At the same time I have only four variants of the product available instead of max 3 * 3 = 9:
 
1. _Blue + Small_
2. _Green + Medium_
3. _Green + Large_
4. _Yellow + Medium_

In the backend CMS product view unavailable variant option values are hidden as expected:

/home/uladmin/Downloads/drupalcommerce-options1.png
/home/uladmin/Downloads/drupalcommerce-option3.png
/home/uladmin/Downloads/drupalcommerce-option3.png

But in Nextjs Commerce I still can select those option values. For example: Blue + Medium:

/home/uladmin/Downloads/nextjscommerce-option.png

**Comment by drugan** [comment]
Requires the #776 to be merged first.

**Comment by cond0r** [comment]
> Requires the #776 to be merged first.

Will try to replicate and apply a fix for that

**Comment by drugan** [comment]
> Will try to replicate and apply a fix for that

I have a fix done already but keeping in mind the issue I've mentioned above introduces major changes in **./site** components so there is no sense to make a PR now because it will create code conflict.

**Comment by manovotny** [comment]
Hey there! Thank you for your contribution. We have decided to take Next.js Commerce in a new direction and will be closing out current PRs and issues due to this change. Please see this PR for more details: #966
