### ISSUE TITLE
@framework should point to framework dir

### ISSUE THREAD

**Issue by Vandivier** [vercel/commerce#341]
1. it's a little confusing / magical how `@framework/api/catalog/products` points to bigCommerce and similar
2. we then look in tsconfig and realize A. I can only use one provider at a time and B. if I want to introduce an API outside of the commercial API I can't use `@framework` to refer to the framework dir, so it creates multiple patterns to represent the same thing and it's confusing

so I'm happy to PR but it would be nice if we just  `@framework/api/catalog/products` ->  `@framework/bigcommerce/api/catalog/products` etc in the code and let the framework annotation refer to the dir

**Comment by loan-laux** [comment]
@Vandivier I'm curious to know how many people would need more than one provider at a time... At least, I wouldn't have thought of that use case.

Also, the main reason for `@framework` being an alias to the provider set in `tsconfig` is for users to be able to switch easily between one provider and the other. If we made `@framework` point to `/framework/`, then switching providers would be a tedious process of replacing a lot of `import` statements across the entire codebase.

**Comment by Vandivier** [comment]
I know it's tedious, but I've volunteered to do the work if given the green light.

Here's a link to my repo where I've introduced a secondary API outside of commerce. From my original comment that would be use case 2.B - I have no info on how empirically common 2.A is https://github.com/Vandivier/futurecaster/tree/main/framework

**Comment by loan-laux** [comment]
>I know it's tedious, but I've volunteered to do the work if given the green light.

I was referring to the amount of work people would need to do after having cloned the repo to simply use the provider of their choice.

But I'm not a maintainer of the project so I can't speak on whether or not this would be considered. I'd tag @ifades or @okbel here to provide more insight.

**Comment by leoortizz** [comment]
I think it would work a little better if there's a way we can clone this repo with only the provider files we need, kinda like the `create-next-app --example` works, with a option like `--provider [name]`. Otherwise, we always need to remove what we don't need.

**Comment by lfades** [comment]
One of the core ideas of this repo, and the framework we have for commerce, is that providers work in the same way, the usage of a provider should be 100% compatible with the others. That way the same codebase is compatible with every provider, but this is also not the full story.

All imports actually go to the core commerce provider, not to each provider, what each provider does is exporting the same hook from the core but with a changed type, so basically it's only required because we pay deep attention to types.

And for the case of the Node.js API it's quite similar, most of the stuff comes from the core commerce, but the commerce provider provides the "handlers" for data fetching.

In a not that long future we'll make the core commerce and each provider a package, so that it's easier to use them outside this codebase (they're agnostic), but for the time being having them as closely matching as possible is the way to go.
