### ISSUE TITLE
Add to wishlist not yet implemented in Shopify framework.

### ISSUE THREAD

**Issue by 1jmj** [vercel/commerce#377]

**Comment by leahtard** [comment]
This is likely because Shopify, as a platform, does not support wishlists. When building a store with a standard Shopify theme, this functionality can be achieved with one of several apps available in the Shopify marketplace. The commerce package currently depends on the platforms to provide the APIs for this functionality. Perhaps a complimentary framework provider could be developed in the future to extend this functionality for Shopify stores.
