### ISSUE TITLE
Error [BigcommerceApiError]: Big Commerce API error (401)

### ISSUE THREAD

**Issue by r3tard3dd** [vercel/commerce#50]
I am getting this error while deploying the new NextJs Commerce.
_

Error [BigcommerceApiError]: Big Commerce API error (401)
--

_

![image](https://user-images.githubusercontent.com/40411728/97689390-c4dcf480-1a9b-11eb-9dd9-b87dca01be48.png)

**Comment by alexduros** [comment]
Experienced it also. It seems that the API keys are not properly created on BigCommerce side. 
In my use case, it was a completely new BigCommerce account and website and I can see after seeing the failed build that there is nothing in my BigCommerce admin panel available (sorry, I'm french - and confiné 😄 ) 

![Screen Shot 2020-10-30 at 15 16 32](https://user-images.githubusercontent.com/629642/97715675-fc12cc00-1ac2-11eb-834c-d2d1bb3e1722.png)

I could see BigCommerce integration twice in Vercel admin panel (didn't took screenshot, sorry) and I was not able to reconfigure it properly since BigCommerce is not yet available as a Marketplace integration.

**Comment by alexduros** [comment]
Seems to be solved now 💪  (after recreating it from scratch). 
However, I guess that the API Keys created BigCommerce are Legacy API Keys which are not visible now in BigCommerce admin panel, so it's a bit a strange / magical to have BigCommerce API Keys created by vercel commerce for you from your BigCommerce instance... but not visible in this same instance 🤔

**Comment by r3tard3dd** [comment]
@alexduros did you try recreating it so many times ? because when I do it, it works sometimes, and sometimes no.
please let me know if you are having the same trouble.

**Comment by alexduros** [comment]
@r3tard3dd  No to be honest, I just retried once after I get noticed that [it has been fixed](https://twitter.com/notquiteleo/status/1322238563090636801) Maybe @okbel can help on that 😉.
I completely removed both vercel project and github repo before retrying. (because I kept the same name)

**Comment by r3tard3dd** [comment]
@alexduros Apparently [it's been fixed](https://twitter.com/notquiteleo/status/1322238563090636801), thank you.

**Comment by Crelloc** [comment]
@r3tard3dd Don't think it's fixed, I still have that issue
