### ISSUE TITLE
OWN API INSTEAD OF BIGCOMMERCE

### ISSUE THREAD

**Issue by roomco-dev** [vercel/commerce#58]
Hi,

Can I use my own api for login and products instead of BIGCOMMERCE?

Thanks

**Comment by jerrylopez** [comment]
@roomco-dev 

Yup you can, but in its current state you will need to do the heavy lifting of coding that out yourself. There's talks and seems like work may have started on building modules for other providers in #2. You can take a look here to see how they are integrating BigCommerce: https://github.com/vercel/commerce/tree/master/pages/api/bigcommerce

Out of curiosity, what platform are you using? I ask because I'm really interested in building a Magento provider module for this and want to see if our interests align here.

**Comment by roomco-dev** [comment]
Thank you for your great answer.

I have custom platform built in PHP.
I want to use PHP Laravel Framework API for Backend.

**Comment by okbel** [comment]
Wonderful! Thank you both. We're currently working on supporting multiple data providers. Stay tuned for updates!
