### ISSUE TITLE
Drupal Commerce Provider

### ISSUE THREAD

**Issue by soft4net** [vercel/commerce#584]
@todo

@see: https://www.drupal.org/project/commerce
@see: https://www.drupal.org/project/commerce_api

**Comment by Flutter-Stack** [comment]
How to write a commerce provider for drupal ?

**Comment by soft4net** [comment]
Please use links i have posted this is a main source of information.
Yet another useful link is: https://www.drupal.org/docs/contributed-modules/commerce-api
Hopefully i will dig into this topic soon.

**Comment by drugan** [comment]
I am working on it right now.

Display of localized individual product, product attribute, product category / brand (designer) listing, search by title, sort by price, sort by date is already done.

I guess the PR will be made as soon as I complete the Shopping cart and Checkout parts of the Nextjs Commerce drupalcommerce plugin.

**Comment by soft4net** [comment]
Great to hear that, thank you! I assume you are aware of project https://next-drupal.org which provides very convenient API to get data from Drupal JSON API endpoints i think this might be helpful: https://next-drupal.org/docs

**Comment by drugan** [comment]
The https://next-drupal.org/ is a cool tool but unfortunately it does not provide any _Drupal Commerce_ related API. 

It might be used to fetch the _Drupal Commerce_ products or any other entities but again in its core all its methods use the generic javascript `fetch()` function.

At the same time the _Nexts Commerce_ use the https://www.npmjs.com/package/@vercel/fetch in its core. So we get automatic cache handling, retry fetch and other things out of the box.

[Example](https://github.com/vercel/commerce/blob/main/packages/bigcommerce/src/api/utils/fetch-graphql-api.ts). Something similar is implemented in the _drupalcommerce_ plugin for JSON:API.

Anyway, I've decided to depend on the https://www.npmjs.com/package/next-drupal  in the _drupalcommerce_ plugin.

At the moment just the the [getAccessToken()](https://next-drupal.org/docs/reference/getaccesstoken) is used but because the plugin is just a basic functionality / display options implementation so the _nex-drupal_ might be used for further _Nextjs Commerce drupalcommerce_ decoupled site customization.

**Comment by leerob** [comment]
Hey there! Thank you for opening this issue. We have decided to take Next.js Commerce in a new direction and will be closing out current PRs and issues due to this change. Please see this PR for more details: https://github.com/vercel/commerce/pull/966
