### ISSUE TITLE
[Big Commerce]  Customizations resulting in 500 error

### ISSUE THREAD

**Issue by adotterer** [vercel/commerce#832]
### Describe the feature you'd like to request

Support for Customizations and Modifier Rules, like how there is for Variants. Right now I'm getting a 500 error whenever a Customization is required, and I'm trying to figure out where to adjust the code. 

### Describe the solution you'd like

Support for Customizations and Modifier Rules, so that products' prices can be adjusted based on these options. 

### Describe alternatives you've considered

Going back go the Stencil template that already works.

**Comment by cond0r** [comment]
@adotterer Can you please share a snippet to can replicate?

**Comment by cond0r** [comment]
At the moment, we are focusing on some improvements at the core; after those changes are fully merged, we will have some work done on changing the price based on the variant’s price, and then we will investigate this price modifier because this is something that needs to be implemented and not available the moment. Thank you for your patience.

**Comment by marcabisamra** [comment]
Any news on this? @cond0r . Really wishing this feature could exist 🙏🏻

**Comment by leerob** [comment]
Hey there! Thank you for your contribution. We have decided to take Next.js Commerce in a new direction and will be closing out current PRs and issues due to this change. Please see this PR for more details: https://github.com/vercel/commerce/pull/966
