### ISSUE TITLE
Multiple "Site" directory

### ISSUE THREAD

**Issue by SaumilNagariya** [vercel/commerce#907]
### Describe the feature you'd like to request

Hi Team,

I have setup an additional "Site" directory in next commerce - bigcommerce setup:

Root:
_ _site 
_ _ _ _tailwind.config.js
_ _site_a
_ _ _ _tailwind.config.js
_ _site_b
_ _ _ _tailwind.config.js

the setup is working fine, but facing one issue regarding "tailwind.config.js" [in terms of UI]
I want to load tailwind.config.js file respective to the "site" directory. Can you please guide me on this or suggest some additional configuration?

**Comment by cond0r** [comment]
Hi @SaumilNagariya, you can accomplish that by using Tailwind presets https://tailwindcss.com/docs/presets. 

Since this project is a monorepo, you can look at these two examples of how you create sharable Tailwind presets as a local package, and then you can add that to package.json & tailwind.config.js for each site:
https://github.com/vercel/turbo/tree/main/examples/with-tailwind
https://github.com/vercel/examples/tree/main/solutions/microfrontends

**Comment by leerob** [comment]
Hey there! Thank you for your contribution. We have decided to take Next.js Commerce in a new direction and will be closing out current PRs and issues due to this change. Please see this PR for more details: https://github.com/vercel/commerce/pull/966
